language: java
sudo: required
env:
  global:
  - secure: hJtGtQBxi9MkHK0RiQB5gIaJnCwj2aKmBgGs9GPkGo6QilAVCbuSzB6CZ7Rx5hyqlUomWooP74ZBGlHPSRPet/rvkDaHdVxqU4k7SAG9f2hi7lz7pYboLPgljPE37y3suyN0RFw4insbfeggyGArSML1MAHI5gofCg7HISwhUKtw4wjI6EKUjIZDU4sEpM5HpObYbn4BOSsOT8KxQkJ+TSNCnpK5vfU4XMKeh2SBUmHXosXo+qZGREBDPJ1xg06YR1zvn9xyfWZR8Nnk87UzB7UohvKrmo+XFw40UIHYIiF3THRUOSRtVC5WfvvT61Xey91/RIP+Nh0f5cxVKkStDE1UJxix54pf2y6Pc6O3xxNrr9ExlkT8NPpVO+CGId9sZLbvHEX3/iWwWBB6ZS7Jf+68ov9y8ZCwXiLSOgUZRELBXMFYSrqAPLTOdyimjGrDctVtCkJdJb9IZweMDR80fxDRKZbHcY2PV5gZ0RC4ra8fyHLKfuVQT7L6VbDqI9iuXOqfWgl/LZ9RLAIdY43XnX32XLRvHkAvj14pMh8L4NxzlZxWy7SY3nmTQsD+3SK2voI/CRgJID92VYdfMbEAkNyWqxPXHoujNNwAMj0P3RQ6Afv3bifCvVzm/AB3RU++q975DMSfy6zTan48iJ0SvrURvTBVZU4WubyxSm2/W7s=
  - secure: bH8fFqRP4vGw55yqGF99esbsYC7+73nqsh+E3iWuhb/SPLYTur/GydExGiWkm4FPkwflz27KuVvrAGC5e4LyGRRVE1YQB1CiHmQaU4PNg82Thbme1KrRylMBVeRz1Pyjcjswd7bWkDgly8elqxqnerqPBENiRQE9jMU9DvkRM6E8jOEeRfWtMkMOjULaGjShAW9vxGfJzCoxWPAFQZrBw9CWa8Nmcc0PvsikgU2ulggqGC29mSTops0F2092bvLJlb88qSb+n/hUfEuW1xMBQfZRAJPXSRnEgOb+RWJjZZcjLkWlur25BM0rFkxY2kAAWneNAfUlvM2iC6j+MdKvj18gkOmz8xtSU8IvuNkuLtoX8BX8kae6NyuvHUnQH+U/w2WHqdzwdrontSAst0BDUfWafT5T7hbZV9w8gYmEB+y1Wivj0nTeqz/AUYH/sI3j9fdx1PFr34LHgc2wDVxvNRrQOXQwdpQF+QDPqQsxMmgJbGM89/ZWd4SbRC6J0Q3tRVv7typ8jDZ7sk0mGB4oCZujQ2fBmeReJvaq/04ZCJoeIKDsgJAVEqkX4QxusreduiVvYIq0kwDs9zEKiEPBbxlz6SQAeMXBDL0jNlUN/Z0Xc06Beby5E6q3h+auzmuusyVBOZAk81HH1Fubm4UPAIc8AWDLgrTSI93CVO04QpQ=

addons: 





  sauce_connect:
   no_ssl_bump_domains: "all"

before_script:
- python -m SimpleHTTPServer &



notifications:
  email:
    recipients:
    - chathuranga.wijetunga@pearson.com
    on_success: never
    on_failure: always
