language: java
sudo: required

jdk:
  - oraclejdk8

env:
  global:
  - CXX=g++-4.8
  - export UX_TEST_PLATFORM_ROOT_DIR=~/build/Pearson-Higher-Ed/ux-test-platform

addons:
  apt:
#      sources:
#        - ubuntu-toolchain-r-test
      packages:
        - g++-4.8
  browserstack:
          username: "eajaz1"
          access_key:
              secure: HyPWyhL5R6bQ59moIuxQ7g0ToHf9LCjaCclp9BFAdZ0qyfw0+xWe5gAAjCdjgeqzJTvmopbOLgSDsjZ9zYp6NKpzVkzYKiIfW3CjlWcCh8u7ZXuF2T4QafI7lPmBYYoxPiTVqzRSENpwHAqsGbgi99bf/Qs3iAmIs8vKWDOjk7Trzm23rmMUJYrxkVq+Qurs5G6zuPO+/IvawfLcS4NXUc+QcOOjzcM9VSqNAsFXhnsMey1tLhV8jyXzmyjOstJ8L9uaR8SsqS5/3Ywm+VstjwBG0h41zQiStBJo7ddiVjAc+gxRDe9DGx1h3pNu+ByJFdkXd00NAmxQ2Z49DdaX3g1MDLa8Nt/TrK9aPcDnf2/ilywBez4SkVnEIS/khEZwgoxHesD5vCL1i9AifEPS/3N4Nw6kvCA8G2vcFRMFghMYtsfkI+kMbI7uwRVVVCI+ELxAWsy/TFwB/IjYOeZV9BT9hCoMyH3PhjmokcaG67uYZ8OK1jpVrmzgKLstC4I/RRnQNU+JfTUjsOrqeUBWAjA0Hp09wFOlXJhcGwxoP/2qSROWCxPuG0jnm3Btzbcr4OwEVZJ9ZcR8vmUyVUiubhpmbC/6+qHec0koxmpOtQPJm1DP3d3fRP7xzv60G2u17J1Uue+iswLg4fx8Py7OFPmbuzm/nBVxtXYgS5j4puc=

install:
- mvn clean install -DskipTests=true -q -Dmaven.javadoc.skip=true -B -V

before_script:
- nvm install 6.0
- nvm use 6.0
- python -m SimpleHTTPServer &>/dev/null &

script:
- export component=elements-sdk1
- export feature_branch=master
- chmod 777 ./src/main/shell_scripts/components.sh
- ./src/main/shell_scripts/components.sh
- mvn -Dtest_suite_xml=elements_sdk.xml test

notifications:
  email:
    recipients:
    #- eajazali.mahaboobbasha@pearson.com
    - payal.dhadge@pearson.com
    on_success: always
    on_failure: always

  hipchat: pQrkiv99DE4e4K1I1KLrR8HZtoE8i3ZGg2bHYLrp@2846476
