language: java
sudo: required

jdk:
  - oraclejdk8

env:
  global:
  - CXX=g++-4.8
  - export UX_TEST_PLATFORM_ROOT_DIR=~/build/Pearson-Higher-Ed/ux-test-platform

addons:
  apt:
#      sources:
#        - ubuntu-toolchain-r-test
      packages:
        - g++-4.8
  browserstack:
          username: "pdauser1"
          access_key:
              secure: Lpevqb65iCnzwRRcJJd1MliSSvCN9VsrTv32oom+tukhgCgdL2tmQQBL8DvY0IfiEa5EfZPfl2JnhpS9Ip2SyoVKi2n0XGz9vZPZmJGcALRVrbwPU0XCCRrmp55W79zwNZ+nkT0JdBJdc2J5qa0FLHMaZFkQA7eMcUJCkyH1zINWOG8TfN98a67qVIClSou55QqQLL+RD4VaD4QbQ9dQIDPWCtS/IvdadoIx9uamMstzlgwyVBja6UGFrbqhk0tSdVcIiJtOQxVY9tARxx/9aBf68d5SY63qVQrPvEw10ctYP+Qw6VJFmjSoGRlaWz8o7whaoDgEOkriGeIpZPT80qOt1rYkvxsri9J5DJd++wthi17ve4dSCS8qDTPsYQVBkMmWB4ZDaFLwTisn2X8pEwh+OPF7AHLXGP3YonUOR9QHhY9oZcT9G28UP+/Y7Ka0y2FdBqovJD6yuASvWHqnQVj1isHXcvLEvvpwEaBsjBOkOSzuNnQ8ANjAnKyrBj62V0tjRTHOcClNjRbJq2oa0uZPGN0oK0jQtkG9VrnM/SrwwdcuPjrfdKqB7m+qyG0LHgU3LEJmhg29ICt1CZCnC9DzuPlS8PhYWyDjfkDIofbgXpzFrKYiBLqJILevApe88T232xD52O/lb2epMceH244hyQ00DlBMc3E4ukyVqsI=
install:
- mvn clean install -DskipTests=true -q -Dmaven.javadoc.skip=true -B -V

before_script:
- nvm install 6.0
- nvm use 6.0
- python -m SimpleHTTPServer &>/dev/null &

script:
- export component=elements-sdk1
- export feature_branch=master
- chmod 777 ./src/main/shell_scripts/components.sh
- ./src/main/shell_scripts/components.sh
- mvn -Dtest_suite_xml=app_header.xml test

notifications:
  email:
    recipients:
    #- eajazali.mahaboobbasha@pearson.com
    - payal.dhadge@pearson.com
    on_success: always
    on_failure: always

  hipchat: pQrkiv99DE4e4K1I1KLrR8HZtoE8i3ZGg2bHYLrp@2846476
