language: java
sudo: required

jdk:
  - oraclejdk8

env:
  global:
  - CXX=g++-4.8
  - export UX_TEST_PLATFORM_ROOT_DIR=~/build/Pearson-Higher-Ed/ux-test-platform

addons:
  apt:
#      sources:
#        - ubuntu-toolchain-r-test
      packages:
        - g++-4.8
  browserstack:
          username: "eajaz3"
          access_key:
            secure: wbfZ84KOy3Ves52oOC0TAJjzzf1VR+/NcyUbzUlI3rot+DfBYGqRmQhkY7vAdkl3AWszo95LGY9bkaHZgsJnL9rDPNH3F/H6TuCiwUBCWww8OWznMdSXrgwb6fEF6h5pO+VBSp6YGOCue96lzEujFJuUmHbJIniRARvtecs/bm8GXob7ynFc4p0+eq3llkT+PwhnQswSDtVUA6GppPW5gAKNPZa+oU9GQINwq9BmpFI/H3+dvf0oAeelSoENtZ5VZwNPHxE80tBFgnCLKDIsyzHJMUtB1+EsoUD+36c4+l9I6g8AQt1Bsdslzs/sYvuPWW56HQz7VEVxnQ2igPbKBQQ/lRJLwMoB43DwKcONkiO7I0L4HG/TMuSAnIDQNWseXpTkky1bQJRR4r6dbV+W5vkroBTcKaafHNkm5hNPYH8AqbCpYTpOdxjOIoIgeFaeE++5R7euKHT/R+WWcYRehtMzWMcACAKBWHbS2uUPxeHtYwjw5bKgd6aYQv0SWJ8+I1k0QJv5jmXj8B1sIbEhCZjIe2T8iCnMMpqQNFgIxScYgiR86WNDsPeczhx8nGAXNTaqAxKjCR79uscbfjlPg4GSVIrUNYnI0bMWgliQQ4x5JlUPA+iRIZIcs3plrhThBNcQafPp99n5GJ8eoDmHysBn6KulHz3TB0Lxwh+sri4=

install:
- mvn clean install -DskipTests=true -q -Dmaven.javadoc.skip=true -B -V

before_script:
- nvm install 6.0
- nvm use 6.0
- python -m SimpleHTTPServer &>/dev/null &

script:
- export component=elements-sdk1
- export feature_branch=master
- chmod 777 ./src/main/shell_scripts/components.sh
- ./src/main/shell_scripts/components.sh
- mvn -Dtest_suite_xml=elements_sdk.xml test

notifications:
  email:
    recipients:
    #- eajazali.mahaboobbasha@pearson.com
    - payal.dhadge@pearson.com
    on_success: always
    on_failure: always

  hipchat: pQrkiv99DE4e4K1I1KLrR8HZtoE8i3ZGg2bHYLrp@2846476
