language: java
sudo: required

jdk:
  - oraclejdk8

env:
  global:
  - CXX=g++-4.8
  - export UX_TEST_PLATFORM_ROOT_DIR=~/build/Pearson-Higher-Ed/ux-test-platform
  - secure: CSyjMyo0qrBozZDRI7LFM6DB2RRemIv9SvEFr4Rq3zt3b3JqQPHLzmvmCvCJhh1xQqDEid/39OZ5kJoUln9qzpHbCxUgN93zlD/oPS6euZv7nx3TwANXx4SZVS/qcNRwkMeOYjRCyOv8pPhT98WHELAiBdHlOuPrxEYOgQ8hDLcKN+zRnM3/GnzLgx+mO6MtKEKl1J1IRDw2LX9JA8mJl1S6pKhe630zs3J4JSpAnfnonPQrnfR47G6SYSw73xrgIKH/uWbXKMA53jaPTi3ReawS8qKXl9OL4mt2HQmPPdX6jnxoy/oUQL3a9k9RSyDoN2ZG5buMXoAY87eAAO4/ro0QlN9Ds/qiiuidrm8+g9/F43E2n5WjDOB10OR0A+tuYIt1nqbRn15RNSGOxEFjMwp5KyIWvi959y7kcSUjm4pggZhfKU1ZB1ZBoXCIT/w39dZF+8XZMtMvvitYiSFUADuwHSFZxt2Ein6H2dAO5jt5MdJra/daYyBnwwM1y/NlTk22FPk83AJqcFgiAX4tbxFLN55k/toCJI299oSh20AUx7NVpmc63399JkwvdaKVFwGz6biT5fwNqLSCKqz72eZrHxEWPSc1wptRhHYaex7RlXmqYAIfODaMJPTPwoEqjOGgFSbT5ZNXUnHtnR3+NrmZ/GQQrO+izUQuYWoWJ2A=
  - secure: GSK5s379plwlpQlrktzokJvjJ8lWtT10GyaEKUszbo9i5nnB2LwQ2Con5jZ47PsMaBGDOHdS70SyLtAySSImk1xzHTGQoQjXQYu6QglIE+YoQGd8KVYVX2lZ0BS/3mlhffdcDBPlGW15LD+fp8X2TxYCzrFVCCgjnuzTgpbt3IMYfRwtrw9shqw093YRXvHMWCPrUK7bwzcwUhsymTiZAdMSSCFIDJVoYAwr6DsrNFCF4HY/Df1Jo4DZYHcSUKHC+sUq+/7R996dSRIv+y0KM7xeYGItJgbFE1NyvsAOQZSENgfCPa4z+GMN/txNa17HpgPcuH4JPEzr9OWfMOMM2DQSuToVt4DVs8OXZQOVIWyHrLHLb3LMnExSATRM6NBpGmZK++pSHeC48GmSNdkTwZBrq/95rMhDo8WDRdzAtlKJjLR/RI09S1WtBdAVHaY7RltyhprVYzufyE8JZLfmczP5hPLjVBldvO2V4uIfaC/2E2g9k/Rsq5nbqZL4BdVJr3PJhHdmUHHNUHDO2agg+q+h4hfiLjfTRTUiR9VtPLAJ2U9MA30wW9htZJsSbohCgSPwPj8qvdzhkqGCQVrZWRa+mAT60oekH7RcPWjPZhId7d7XDI3E8TJgmD0VQ4y6l36pZatVnZcf3BbpXvTMP7biHW+buXdKyLjRYfrPqfo=

addons:
  apt:
#      sources:
#        - ubuntu-toolchain-r-test
      packages:
        - g++-4.8
  #browserstack:
          #username: "payalpda1"
         # access_key:

install:
- mvn clean install -DskipTests=true -q -Dmaven.javadoc.skip=true -B -V

before_script:
- nvm install 6.0
- nvm use 6.0
- python -m SimpleHTTPServer &>/dev/null &

script:
- export component=elements-sdk1
- export feature_branch=master
- chmod 777 ./src/main/shell_scripts/components.sh
- ./src/main/shell_scripts/components.sh
- mvn -Dtest_suite_xml=elements_sdk.xml test

notifications:
  email:
    recipients:
    #- eajazali.mahaboobbasha@pearson.com
    - payal.dhadge@pearson.com
    on_success: always
    on_failure: always

  hipchat: pQrkiv99DE4e4K1I1KLrR8HZtoE8i3ZGg2bHYLrp@2846476
