language: java
sudo: false

jdk:
  - oraclejdk8

env:
  global:
  - secure: 2jtw+Rm/NY9su8NA/L7DDcy19H1aCy4Em4l6MQq3+cTuy5oaFAHmYxkpmwNBZF2r/LJqYuFcvvxNkNh5M2Agn7R2AJ0H8AOMKpddfz+VKLHF8BIgiJQ5PH0zfsBv74Ke+Z4phVN+n41quoD+NJDo32NdGhUkHMqlwzBk4eV9CiMo96cZq+29lfdhpot+bc5iSk/pddp5uFUehikn3CXf66zvmYi4h4W9XiSZ+dt4PdvHkxJu/sFKvuodcK84UJnpOsd0tMH63y3mE+OwrElHZhpgYm9EbBTpePM+hZlXkTmDsO/BJC4HWb3ns08W5KA+OMC/LnZKi0N4Y9tMhgWURk20ezBTg02sx8FkDD0z2UJYYXwPrnhsy/BRqhqC+7xN3393un2Q88zGwKXbYqDGsHE9uRGOKPJdO4RqcoMeU5ZQ0ZooYLYNWezigRhUjW0UyRpt4FWS14sIvYCgCwZ71Y9QdmLalLVKOl2/J4ryuE8OOBWe/HFZVNL5JD/p/5z5Ql2lC1gh71SgxGXuz+QB/c1AXNc6cPIyT6wzjkN8aqjikSj6KWErfcbeCFZTUDb+dKZPlJI8UpMmYyCkvAHmP3PT4hPkyaINiIoGzN5Wkt0d3flBx4h1HN1QvSqoYNOiLjxGlTg1h3dw7pjRvs1v1TNTc1BMZPZpKINgCS1KYvU=
  #- secure: UX8IPlfuE1XvcEJwZiv6eM4rsPO3cxapgywxLqOObVt2wypsSiHo0NkkYJet5MfgpPYIviy8FP2poZUG3PkSc+x+zWtNf+usYBMeuhjbaW4sUvjznwhOpq5qphEhBlf7L9OCGd5Qv0qZjoHNSD5stfSOJd8Z53miFJ4O4KjpRNVFCJYfn1ple5WCoCjATbMl6bZqbigYU3s0jaXp9oue8cYVCttm/ahyQ+O9ya/NvGr93mr+dIr0scXDAMDM3aUTB8VZcRJ46Y9jy8MJ3nQTlJr1/+Gm2ujdpzgloVlQ2nBgSPAjvxJv3RQIZZsIYm4SoRntpSilYR91KZFEirUkZON7E6/bhb8N4mJTnqo5UPcHJl/8teF+SfdURiYDc7XQ3i94aiWKzOdzNBWi0OZsAU483jn0+kuTMafsTZ3EOGMMequZecdfn4PG47Ahq29Qy2s/92CECNoFiZL8BXCAbb4ecnS0fShe/79qsbG7OyTHkJlDPYhoQY+2eCVv0Wnrprv/sThzmnrs8QpAyPWAQ4siJ0y8Q8mIeDUWWZ4C5cll4Mincom7tdOOapuCsNLCxWn2LJeyCRPzpbgJBW4I2R76Ed2yjR1yuh4l5W0HB1604rRh+ImPpHn8ZYDYxrk284aI2RzhSNkUU6bdx2tgheJs2uFtDgXKIpZtlw1Kqks=
  - secure: KADmbjUOpiUSmZ5tz97twFS5knNScvzRMv+gpxVrVVCzO5S8MaEuT04Eu95aPifbTGm54VeSEamPC3wegY8ybmTiK/hg4vpOKhe6bh7FLjuy9nOGnDbON9viq1tgsJapZjyY9VlmBoTnAnYMEk+1IApMfmM1fLgSS2oGnai1sRU+1mP7K9tn+W3TzSCTEsZCUrP9LA5A47/bsN9nfkme1kYx8GCi78+5Z+e1GsQDDBFnEm0ErwcwrVchI2V6wUSFS+XkLdjru9QQWVk+9Xx/l3izQs5EWPIw6rY4SqHEuIJjOOw4JGHHxuEUhagoqlP0pKK054o0TUOh5/TXMn18SnUbkW669iXlghKuWyVcyCPYze6nNYWbUuK54ExRrxC6iv6cV/9Hr5QwkTqzrcAHMTfQUsdMWoEQGFxb6o3sxqYDjm/eE1m+rHqo4SvfyTVg1AyiQyVTchLaO33+i2ZoMZCxkOx9ZbpYsX2ZJOcD6xy7txKAsenxJj5iHmxGvS4Plbd6XRR8zkc6x+WKA36Hno/kH1u4bwYQOZ22mPL/0vKS6omAVGoNr0resd+A8LMDuLiwOIVBjGS5Q6/GSiIHNip4LtI3E/01SY3VHDhB/N9GIzyVzjGrYr27oQTgT5eIOVmeB5/ar66LY/BlexwtdvVU7rDyKdmbqQPLW0bg5/I=
  #- secure: P8t4vLidU5cVGbHllIiUkZFeajPVwGMaipIe+o1rm0FQO7bciJawoXJSOcTSMJhN1RMFSzF0ZaAbo4EiLJcx2VGxppyiR8LLYDMXt8E0QuW+Yy91K8TdjJOMrgJlWJsWmK8pRVjQSeLP77xDO7HvA/vfJPSf3d6DLeeFQ+Y+hu1/u+HwTUxZ4Ta79Iy87U6y4tyZCx/0H28Xvb9cMRM0m1urPJ15EGyDGJfo9rmn77VKrdFy2q5QDjF/O8o6fNCZ+lXlyWxEnxawETKjX3nfOTM1Lm2pfLfKC3+zhLQ5ukQPbrhDXK5QHK03nppv7lUMtN+BskWyJCZnC7l4VkZyYaOumnTENuDXK4O7Lq4swv3jXOcWZT3ZLpRG0/Ydw4rFwPOW4VCVEO10tVdxyi+hro4C+CgNxalXyXdLCAGqEYkIH0RsKp3hPoOaD00pstobGvEw/ZWIhinkk8YNAJ4MliKINonFBHUe5TEt4p4QV2awee3Q8ajn9F0BhpNsS733dkSIV1BvWgj/BwVllN4kxNP0XoCFMVa7lifykFr/TI39ilwUFK5wOM36kmVTTLHumB4qVdybrqOcG2amjsTgql9MbBxuD0tzBpLJzKacCXB/W8Z148oYFQQSkX6KM5Cp39a2HiLmH2oZrLk8xrVNxUcGqS+xYW3S7CEYSxxp+hs=
  - CXX=g++-4.8

addons:
  sauce_connect:
    no_ssl_bump_domains: all
  apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-4.8

install:
- mvn install -DskipTests=true -q -Dmaven.javadoc.skip=true -B -V

before_script:
- nvm install 6.0
- nvm use 6.0
- npm install -g local-web-server &>/dev/null
- ws --log-format none &

script:
- export component=elements_sdk
- export feature_branch=triple-template
- chmod 777 ./src/main/shell_scripts/components.sh
- ./src/main/shell_scripts/components.sh
- mvn -Dtest_suite_xml=elements_sdk.xml test

notifications:
  email:
    recipients:
    - eajazali.mahaboobbasha@pearson.com
    - payal.dhadge@pearson.com
    on_success: always
    on_failure: always

  hipchat: pQrkiv99DE4e4K1I1KLrR8HZtoE8i3ZGg2bHYLrp@2846476

