language: java
sudo: required

jdk:
  - oraclejdk8

env:
  global:
  - CXX=g++-4.8
  - export UX_TEST_PLATFORM_ROOT_DIR=~/build/Pearson-Higher-Ed/ux-test-platform

addons:
  apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-4.8
  browserstack:
          username: "payaltest1"
          access_key:
                secure: fyTRrIqsdu5b1keGfibdd3fhbC0vnC23Kdwj2uQbTPCGi8hLPvYv8XxE6evt560YMonoPbAxAIMIWuGMXhYtuFdUaeA34uNJdXp2dARbSmW+4alpfgZa/rFbr5H3w43GcLCBuqPJPR7SRt8Z59iRyXN8ZLkZl5FqnylwWWvdmScvgGOh+PUQuwyhQ6ktlIkW/U4jsflMRtQNwJudIyCFnliaLdNT8NnxO4LjUubIVP1WjHCV36Mn/oZYvnOurjApZdQHbjydhYXf0G9FVHMpPSsEZqGJMhVwBXur/1KGXo4aD5N+WqSKD/gnpBgLFe2iYfkhFuwswYDOZahL3e9ywEyJ93IJ+16TIjiyRTbCnYgt1UiBODShKyWw/xsQFzB4TQwNsmysoqcGNOaIBtGygRbyau60QLtohwwLYgytKHxSyDIL+GDZ1duFMdGmWaCT8kUp/Zt/RyIcKnF7d7fCvuF1ozrzJ5QbNAyQUn2lykcGLHWjooHBWDamASEHB/a2Eb2ljCvRGHxP60Ntc2witxmxcCVpBwBEpL+aVDpxorgV1vOf7fw/DB5He5jZKb9PorPZCQNVvdQ1Ju2tBLfXv/IwsF5LCnH7cKauOOY+GamHv6N9Ot74EyejlBFr/Lq17TOe7arLHs3V0zEQicsrx8gyIi1lfn8vhOsEDWYJzvY=


install:
- mvn clean install -DskipTests=true -q -Dmaven.javadoc.skip=true -B -V

before_script:
- nvm install 6.0
- nvm use 6.0
- python -m SimpleHTTPServer &>/dev/null &

script:
- export component=elements-sdk1
- export feature_branch=master
- chmod 777 ./src/main/shell_scripts/components.sh
- ./src/main/shell_scripts/components.sh
- mvn -Dtest_suite_xml=elements_sdk.xml test

notifications:
  email:
    recipients:
    #- eajazali.mahaboobbasha@pearson.com
    - payal.dhadge@pearson.com
    on_success: always
    on_failure: always

  hipchat: pQrkiv99DE4e4K1I1KLrR8HZtoE8i3ZGg2bHYLrp@2846476
