language: java

jdk:
  - oraclejdk8

env:
  global:
  - secure: O4/I+EHfFOLjxV8IlGCLJDUFWblDmF11W+QwpusG4K3gztllM9AxJO5pwI4COo3z4MOWjsZy06GBB3qNNyEzI0Zn9spFKSDuds4PyTBpDN6Iz0YvNqg65fCSLkBXmHTL1xAiHOigeIuOBPfV8wQyg/fecc1/OPdKScuBgpy6hFOdOKv1a5+K9Q7ih0VEBAs+kHn+YRhsPypdQxtSSkrrCHOnPYc5gydjqlEblKRp1idk/scyaPHBz35yVroIo9SCxPQe5h2YHdcMhYIYgvZo6Z1394u1NofoeBNWznXKSal3hS2LuHW4zgL3L0rdr1fOstBKiX+di58Wi0fsRgdOTNVJs5xJJyJyxYrQzp+SW9g/b1cxeg+LvKkVl9xokFq+TDXJ7+L1dfRBPURO2L8vsSph4yc3VS8fFwbEepr/qbwRA5oowSA2jdCqSK8pIoO2e+Dx0hoWQ1YLWj+HkdQYLRIflq6LaGtIJUEJPjzY5rPA5rjA8EZkTrq2H+rpPDsXwpDSi8yGVmYh2+dhbTb0D6VCI4+9RouRlwBD0P2hJhQr892sS9h3Y8j3FLw8inuyCr/761sCBM9P3gspsv8BO61/ZcyEwsGIGEHgp4EG0Qli7guqLZzuRbqvPD8PKvi5NiM0MeFU7zGTdxricUJdHtEp7iBjPMFOLptHG9NQohY=
  - secure: 004aIT9RNRVGwl3SG2z9yC2PtsGCmsUGEgFc2ZTAKIx0C5mD195+R6R0hR901eJQQ+M+5/nFxFTAWBe7SajTrpER5jdtWxAUPgxCo22Hv+Fz/W03GSHaio42MvXDwo47dOJ8qxkv06zds66zKaxXXpN7SWVqS0zYw2EgJxLNMI5PHoT6H2cXX35BWR1sHfVhkMmwPac1sYtau6b/tYvnQRGrk/VNcfunYHhryS6hgToBgSvDeQbTkBp8KZJRpxp7tHw873pmSjrfi+vA1NAUA/y4YWeLarbnIbzn0Yu4IoOMKmag5Fw6D4x2RVa65VbM45n66HGo79om7C2CiU7Me84Gj7bMdDSeqmOm/t5A0AhgYyLem3HWZVTF+SeNDvtEaWt57h8a4GbCdcwfqy3hFpo+FzMV3mQBwWzg8cEZ74Nq0RBsYrGAifwqfm9YkIGUpSLuAmOCmjx9nxv3nqRU4vYPPvtiqvYhXU2DkcpiNqBQCo2J6OlPqb7X1Gcklh/sJQz0Ando0Loz1bFem4Lixpk705u54Y+DsgSe5rdvxK/wN68sKg10AWb5csgApTAldE9cOCNYgImDyg7tXvRs0aQcWfd6EJDN4THHNFYo03Q7H9Q8oTaA2RqPT0ypOLmGYw5Khxgz1Q0Ae05xW3moIwetixyyQG5k/wytUTv0vZY=

#  - secure: UX8IPlfuE1XvcEJwZiv6eM4rsPO3cxapgywxLqOObVt2wypsSiHo0NkkYJet5MfgpPYIviy8FP2poZUG3PkSc+x+zWtNf+usYBMeuhjbaW4sUvjznwhOpq5qphEhBlf7L9OCGd5Qv0qZjoHNSD5stfSOJd8Z53miFJ4O4KjpRNVFCJYfn1ple5WCoCjATbMl6bZqbigYU3s0jaXp9oue8cYVCttm/ahyQ+O9ya/NvGr93mr+dIr0scXDAMDM3aUTB8VZcRJ46Y9jy8MJ3nQTlJr1/+Gm2ujdpzgloVlQ2nBgSPAjvxJv3RQIZZsIYm4SoRntpSilYR91KZFEirUkZON7E6/bhb8N4mJTnqo5UPcHJl/8teF+SfdURiYDc7XQ3i94aiWKzOdzNBWi0OZsAU483jn0+kuTMafsTZ3EOGMMequZecdfn4PG47Ahq29Qy2s/92CECNoFiZL8BXCAbb4ecnS0fShe/79qsbG7OyTHkJlDPYhoQY+2eCVv0Wnrprv/sThzmnrs8QpAyPWAQ4siJ0y8Q8mIeDUWWZ4C5cll4Mincom7tdOOapuCsNLCxWn2LJeyCRPzpbgJBW4I2R76Ed2yjR1yuh4l5W0HB1604rRh+ImPpHn8ZYDYxrk284aI2RzhSNkUU6bdx2tgheJs2uFtDgXKIpZtlw1Kqks=
#  - secure: P8t4vLidU5cVGbHllIiUkZFeajPVwGMaipIe+o1rm0FQO7bciJawoXJSOcTSMJhN1RMFSzF0ZaAbo4EiLJcx2VGxppyiR8LLYDMXt8E0QuW+Yy91K8TdjJOMrgJlWJsWmK8pRVjQSeLP77xDO7HvA/vfJPSf3d6DLeeFQ+Y+hu1/u+HwTUxZ4Ta79Iy87U6y4tyZCx/0H28Xvb9cMRM0m1urPJ15EGyDGJfo9rmn77VKrdFy2q5QDjF/O8o6fNCZ+lXlyWxEnxawETKjX3nfOTM1Lm2pfLfKC3+zhLQ5ukQPbrhDXK5QHK03nppv7lUMtN+BskWyJCZnC7l4VkZyYaOumnTENuDXK4O7Lq4swv3jXOcWZT3ZLpRG0/Ydw4rFwPOW4VCVEO10tVdxyi+hro4C+CgNxalXyXdLCAGqEYkIH0RsKp3hPoOaD00pstobGvEw/ZWIhinkk8YNAJ4MliKINonFBHUe5TEt4p4QV2awee3Q8ajn9F0BhpNsS733dkSIV1BvWgj/BwVllN4kxNP0XoCFMVa7lifykFr/TI39ilwUFK5wOM36kmVTTLHumB4qVdybrqOcG2amjsTgql9MbBxuD0tzBpLJzKacCXB/W8Z148oYFQQSkX6KM5Cp39a2HiLmH2oZrLk8xrVNxUcGqS+xYW3S7CEYSxxp+hs=
  - CXX=g++-4.8

addons:
  sauce_connect:
    no_ssl_bump_domains: all
  apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-4.8

install:
- mvn clean install -DskipTests=true -q -Dmaven.javadoc.skip=true -B -V

before_script:
- nvm install 6.0
- nvm use 6.0
- python -m SimpleHTTPServer &>/dev/null &

script:
- export component=compounds_sdk
- export feature_branch=ELEWC-2316
- chmod 777 ./src/main/shell_scripts/components.sh
- ./src/main/shell_scripts/components.sh
- mvn -Dtest_suite_xml=compounds_sdk.xml test

notifications:
#  email:
#    recipients:
#    - eajazali.mahaboobbasha@pearson.com
#    - payal.dhadge@pearson.com
#    on_success: always
#    on_failure: always
#
#  hipchat: pQrkiv99DE4e4K1I1KLrR8HZtoE8i3ZGg2bHYLrp@2846476
