language: java
sudo: required

jdk:
  - oraclejdk8

env:
  global:
  - CXX=g++-4.8
  - export UX_TEST_PLATFORM_ROOT_DIR=~/build/Pearson-Higher-Ed/ux-test-platform

addons:
  apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-4.8
  browserstack:
          username: "payaltest1"
          access_key: "BZERJz99zPAMGt9xS6qx"

install:
- mvn clean install -DskipTests=true -q -Dmaven.javadoc.skip=true -B -V

before_script:
- nvm install 6.0
- nvm use 6.0
- python -m SimpleHTTPServer &>/dev/null &

script:
- export component=elements-sdk1
- export feature_branch=master
- chmod 777 ./src/main/shell_scripts/components.sh
- ./src/main/shell_scripts/components.sh
- mvn -Dtest_suite_xml=elements_sdk.xml test

notifications:
  email:
    recipients:
    #- eajazali.mahaboobbasha@pearson.com
    - payal.dhadge@pearson.com
    on_success: always
    on_failure: always

  hipchat: pQrkiv99DE4e4K1I1KLrR8HZtoE8i3ZGg2bHYLrp@2846476
