language: java
sudo: required

jdk:
  - oraclejdk8

env:
  global:
  - CXX=g++-4.8
  - export UX_TEST_PLATFORM_ROOT_DIR=~/build/Pearson-Higher-Ed/ux-test-platform

addons:
  apt:
#      sources:
#        - ubuntu-toolchain-r-test
      packages:
        - g++-4.8
  browserstack:
          username: "payaltest1"
          access_key:
              secure: W7ZwoNARh+VXx5mJrfTlm5oHbB/gyXzG6RT3nHZv3Me0S82fi2Mp24EtdTUaeMUcGK0LPqrzAxeOJH1anQaQZ6qkW7YHC0ZlUfI5f5W82H/rSvTnfTpdQPv7QzfYVelqELDP9S5aflYPlcgmo8jSf0yxBcMiSewX+hDBBq9MBEvFuEHg0gkonHSWYvlweNhTcRxVOf7PuNXzuXpHf0/Tz0/SpqM3RUQSybqpvllsIxyIH1K2vSBhOgpHMt/F3VL30KnQZxFkfohCIlyusjnMKsm+6LXeAHN1dbOpUHoxOgWT+lkWMVwqPHKFRlSSI/rJz1QbEcFnlFU6tnl7qOIYdaHL2G+nUaqC4l9DJOaj10ub4Q2CjKBSOMpbpWzEsWSrdshHVQ1FHBSwFtbN1cCQZG8EiVP05jNQwTevIHZc3sFtOzi90Al6IOCWSnTnwj6OU1dtFmynPxrnzMZjRCcGgXsWFcAeVkncn1OtgHhilYBPcbump2X9UcJA2dl7eE5L61ipQABch/sAa8a9PSfRWT1O/dbQ+Y36mml/LAts6RIl71VzTt4n9mZp7Izlzn6s6PqogyyASK0pMeXdp3DzRSfk45uhwzYTmm7kP3YQ22YZ2Y5Z8ggcmqB9Ww0cPX2ztvbEooyy8TfezQI9Bg8iVKWU003PbF+qYS4D3fqyZOg=
install:
- mvn clean install -DskipTests=true -q -Dmaven.javadoc.skip=true -B -V

before_script:
- nvm install 6.0
- nvm use 6.0
- python -m SimpleHTTPServer &>/dev/null &

script:
- export component=elements-sdk1
- export feature_branch=master
- chmod 777 ./src/main/shell_scripts/components.sh
- ./src/main/shell_scripts/components.sh
- mvn -Dtest_suite_xml=elements_sdk.xml test

notifications:
  email:
    recipients:
    #- eajazali.mahaboobbasha@pearson.com
    - payal.dhadge@pearson.com
    on_success: always
    on_failure: always

  hipchat: pQrkiv99DE4e4K1I1KLrR8HZtoE8i3ZGg2bHYLrp@2846476
